spring:
  application:
    name: consumer-user
server:
  port: 8200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #注册服务时候使用的是服务的ip地址